const fs = require("fs");
const filePath = process.platform === "linux" ? "/dev/stdin" : "./input.txt";
const input = fs.readFileSync(filePath).toString().trim().split("\n");
const ans = [];
const [a, b] = input[0].split(" ").map(Number);
ans.push(a + b);
ans.push(a - b);
ans.push(a * b);
ans.push(Math.floor(a / b));
ans.push(a % b);
console.log(ans.join("\n"));
